# Register
POST http://localhost:8080/users
Content-Type: application/json

{
    "email":"ot2@email.com",
    "firstName":"Ot",
    "lastName":"Ot",
    "password":"Otaxx@12",
    "passwordConfirmation":"Otaxx@12"
}


###
POST http://localhost:8080/users/verify/6476a71d71110f390e440034?verifyCode=a1845fa7-64d7-4a22-8a02-9f688e91f009

###
POST http://localhost:8080/users/forgotpassword?email=otavio.bene@outlook.com

###
POST http://localhost:8080/users/resetpassword
Content-Type: application/json

{
    "email":"otavio.bene@outlook.com",
    "passwordResetCode":"bfb7c7f3-aca2-43d7-a13d-cb2669bc7173",
    "newPassword":"T@v!nho12"
}

###
GET http://localhost:8080/users/me
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc5NDdmYjY5YjM0MWE3YTQ0ZjQ1MjYiLCJmaXJzdE5hbWUiOiJPdCIsImxhc3ROYW1lIjoiT3QiLCJlbWFpbCI6Im90QGVtYWlsLmNvbSIsInRyYWRlcyI6eyJzaG9wIjpbXSwic2FsZXMiOltdfSwidGlja2V0cyI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDYtMDJUMDE6Mzg6MDMuMzg1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDYtMDJUMDE6Mzg6MDMuMzg1WiIsImlhdCI6MTY4NTY2OTkzNywiZXhwIjoxNjg1NjcwODM3fQ.VTDz_F7OB4HhnV5-y14GysudsyVzeKjOymmP_LC2UtKdB9R88P7DfNwPcsol0vxsN3vA_xr9J9yTWWxy_oUyS8NlRENapBN1eGXMoLv7sSNxOrrJzFgH2DpWqUqEr9qBwTciSq3X6sAtSi_ODMNyxMmXPz2N19NEAlQSUtwcfE7jipGK66w5RGEsJ0humdnIh_QlJHwW42LAxGxZWAmk1fTwhdfB36Ps-B0u2lrHaeBcySV7WZG8M7fnELOTRAym_YeW-dA-IDyLDJQpnFiu6eGKh5bHdXgdWrl-7fwxkq2rq5_biUVESCn6hmieL0b8Wq2Sj3Jg-hvS8ruoJtJdIg

# Login
###
POST http://localhost:8080/auth/sessions
Content-Type: application/json

{
    "email":"ot@email.com",
    "password":"Otaxx@12"
}

###
GET http://localhost:8080/auth/sessions/refresh
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uIjoiNjQ3OTQ4MzE2OWIzNDFhN2E0NGY0NTJkIiwiaWF0IjoxNjg1NjY5OTM3LCJleHAiOjE3MTcyMjc1Mzd9.V3I9vL4gpOWp62awrCZ1IrXFaySWy7bsyPR0sfIT06eUGm2gslT-pEvrst0ZOl5fH7ghPhkQXzH-tYAxB9xXHBhKUsbD25elcbiXYyryGxlwscwwlTU0h5y0CmW-75MrxIas16wgmXC7nTw0r_RHu1jADOLIl3TG38_otwR3hcU3LG29TULWZ_qHi6sOngh21a-czCfnZOsy_t3T8Er1EVVtumOPG4tLWokZZzpFvLMJn8qCSz5J-45JKP3xaINSIWS-r4U9miWgiKsFqsabIDwM9TdTdaSzgV61uPoeXowTlcAj4kG8YUQnIbNEd3hvUzRNXI_eDyCYpJejPke68Q
 
# Tickets
###
POST http://localhost:8080/tickets/new/647947fb69b341a7a44f4526
Content-Type: application/json

{
    "title":"CS: Session Teste",
    "category":"game",
    "price":100
}

###
GET http://localhost:8080/tickets/647947fb69b341a7a44f4526

###
POST http://localhost:8080/tickets/trade/647947fb69b341a7a44f4526
Content-Type: application/json

{
    "ticketId":"33850342-828b-4d7e-b507-bea874a69946",
    "emailBuyer":"ot2@email.com"
}

# Trades
###
GET http://localhost:8080/trades/647912fa8e34b4ac28eea945