# Register
POST http://localhost:8080/users
Content-Type: application/json

{
    "email":"luis@outlook.com",
    "firstName":"Otavio",
    "lastName":"Benedicto",
    "password":"Otaxx@12",
    "passwordConfirmation":"Otaxx@12"
}


###
POST http://localhost:8080/users/verify/64795787ea07070452cac7b0?verifyCode=0c21ac75-6950-41bc-b5fe-6c65b89c3ed0

###
POST http://localhost:8080/users/forgotpassword?email=otavio.bene@outlook.com

###
POST http://localhost:8080/users/resetpassword
Content-Type: application/json

{
    "email":"otavio.bene@outlook.com",
    "passwordResetCode":"bfb7c7f3-aca2-43d7-a13d-cb2669bc7173",
    "newPassword":"T@v!nho12"
}

###
GET http://localhost:8080/users/me
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc5NmEzODc0M2I2MDI4MzZkNWU5ODEiLCJmaXJzdE5hbWUiOiJPdGF2aW8iLCJsYXN0TmFtZSI6IkJlbmVkaWN0byIsImVtYWlsIjoib3RhdmlvLmJlbmVAb3V0bG9vay5jb20iLCJ0cmFkZXMiOnsic2hvcCI6W10sInNhbGVzIjpbIjY0Nzk2YzcwMTU2ODVlOWMwYzUyMWUyNiIsIjY0Nzk2YmY4OGFjY2YzMDc2MzczODg0ZiIsIjY0Nzk2YjQ4ZDljZGFlM2QzNTY0MDQ1NCIsIjY0Nzk2YWY0MmVlMjYwYzk4MWZkOGY2ZiJdfSwidGlja2V0cyI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDYtMDJUMDQ6MDQ6MDguNTYzWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDYtMDJUMDQ6MTM6MzYuODA2WiIsImlhdCI6MTY4NjAxNzA1NiwiZXhwIjoxNjg2MDE3OTU2fQ.Ff8eu6fDQ80OmU1hSzWfGpkLWwa5xd9v3drTUZplExKAN5I56VRWOpRjY1t--CJ_fOr5aK6DVL_C75GoS704mEfrcz2GiISMnE1chEEjR0MupWSSGx-uOn-W7HHyRp6b1oykJ-Y1p9939jbi3cg0r3gCN91CMINWVvMhG8kWmQU_fA1NALyPzLf8jXHYvgPgauDOlWyjWjaffymvY0XIe50dn3FUUjy6Nn4Q1gkqWKf44PJsF4lFpGzuCGbe7wp8VdWOVPE_ib26VN0bLRjBS3IPEJ-Zd7xCpyvknX7PBZApmmsFj9mD7FH7TYN71o8lTae80kNBWhXXvJYHAc5qBQ

# Login
###
POST http://localhost:8080/auth/sessions
Content-Type: application/json

{
    "email":"otavio.bene@outlook.com",
    "password":"Otaxx@12"
}

###
GET http://localhost:8080/auth/sessions/refresh
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uIjoiNjQ3ZTk0MjAwOGFhOGIwYTkxMzU0M2VhIiwiaWF0IjoxNjg2MDE3MDU2LCJleHAiOjE3MTc1NzQ2NTZ9.Vc-YlA3AWl9WRlO5JrnX5ByASoDyvbBDxfvm4cQJLSe48LWdvltXtQ3oAZQ0mI0jNbbwFUIZdpdnlyqL4m9wrp43pthcozuKRGpjsRF1WWjWy_Dlf__RYGSMpel9_3BsQ0IAOxly7LViUJKc0xV7WQbbemH9BgruqRFSd4GbL48IbOTBx12NCkQu1vPFUufck97P-SJ2ESY4Iyst6AVNm-KqyDSPT2sgFLxISqmAe539C9hKdtmSCRbH5eAhymmGw900rkOwJjUcn6kITY9mK9znK-xaqmg11G9Cki4P63ATEuCGvWMl3oTo3IqYrNCqYQ9YW2n5zEJcVWG_GszbUA
 
# Tickets
###
POST http://localhost:8080/tickets/new/64796a38743b602836d5e981
Content-Type: application/json

{
    "title":"Tusca 2024",
    "category":"event",
    "price":125,
    "description":"Ingresso 2 dias do tusca 2023: DJ GBR, Matheus e Kauan."
}

###
GET http://localhost:8080/tickets/64796a38743b602836d5e981

###
POST http://localhost:8080/tickets/trade
Content-Type: application/json

 {
    "emailSaller":"otavio.bene@outlook.com",
    "emailBuyer":"luis@outlook.com",
    "ticketId":"28b241f0-26a8-4fff-b4a6-836ba858bae0"
 }

# Trades
###
GET http://localhost:8080/trades/64796a58743b602836d5e984