# Register
POST http://localhost:8080/users
Content-Type: application/json

{
    "email":"suporte@hebrombeneficios.com.br",
    "firstName":"Otavio",
    "lastName":"Benedicto",
    "password":"Sup@1a2b3c",
    "passwordConfirmation":"Sup@1a2b3c"
}


###
POST http://localhost:8080/users/verify/64795787ea07070452cac7b0?verifyCode=0c21ac75-6950-41bc-b5fe-6c65b89c3ed0

###
POST http://localhost:8080/users/forgotpassword?email=otavio.bene@outlook.com

###
POST http://localhost:8080/users/resetpassword
Content-Type: application/json

{
    "email":"otavio.bene@outlook.com",
    "passwordResetCode":"bfb7c7f3-aca2-43d7-a13d-cb2669bc7173",
    "newPassword":"T@v!nho12"
}

###
GET http://localhost:8080/users/me
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc5NmEzODc0M2I2MDI4MzZkNWU5ODEiLCJmaXJzdE5hbWUiOiJPdGF2aW8iLCJsYXN0TmFtZSI6IkJlbmVkaWN0byIsImVtYWlsIjoib3RhdmlvLmJlbmVAb3V0bG9vay5jb20iLCJ0cmFkZXMiOnsic2hvcCI6W10sInNhbGVzIjpbXX0sInRpY2tldHMiOltdLCJjcmVhdGVkQXQiOiIyMDIzLTA2LTAyVDA0OjA0OjA4LjU2M1oiLCJ1cGRhdGVkQXQiOiIyMDIzLTA2LTA3VDIzOjM1OjU5LjU0OFoiLCJpYXQiOjE2ODYxODEwNTcsImV4cCI6MTY4NjE4MTk1N30.W1lyq21wnIeAo02dkqaWp6MArGkr_HBfKzldgljU4WCBqXhfkZDvd81dE21ynBNZQdMGUluPHWkXGZqb6ykahdr7kbHBBLSo1TB-irsDn3kS_EJN3tq5t-nrYGIb7WuzifRKjyiKGYEHw3Bbclry5YG7iq6rV30wiDf0sq3ILGbN0Y1squRT92FDnuSZnhrCNfTzHB_F9tI4O1e6H2iudOYPyM_W9nrxd03zueQvrnZR8pIaYNYjls8rBnkkT9T7WMSGYPbIVfWgOhdAJjeBH4HNupjwSJiM2Fqvq6R3D78_gDZfWj-20Z4HgArgMECTni6TmqhAIBt4MThGSSVaVQ


# Login
###
POST http://localhost:8080/auth/sessions
Content-Type: application/json

{
    "email":"otavio.bene@outlook.com",
    "password":"Otaxx@12"
}

###
GET http://localhost:8080/auth/sessions/refresh
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uIjoiNjQ4MTBiM2MyNmQyNWVjMzc4OTEwMWQyIiwiaWF0IjoxNjg2MTc4NjIwLCJleHAiOjE3MTc3MzYyMjB9.GpZ_IpleXHhUSaRoPID906j0NkiHYzJEKCf3kCtBIETrkqxo9xUo75OvX9eqfxhC8y3Fo7er5Ap_AogUwfqX4wSwAZ-EDXeaamCArbaMeOmWtsi8gOHOE-6uJuSCKwpMM1f30uN9mBUh-BuWlyftp9rnPXa47ZSbDdRGvySutDASqS38Gr5IRmod26CBZVGIYJY3pHq4qparnaMWbwQi2gZ0QJa7cN5nyWa75m_9hzakB4tnnav_C57K4FltvAIXABtNuewXvJDkyoyjFjVAqn6xBhIitcTAepqJ_wZ9V6RieiDTCa_M0QBb9ikz6w1Qq_C5cDu0ND2UuNtIsY6-FQ

# Tickets
###
POST http://localhost:8080/tickets/new/64796a38743b602836d5e981
Content-Type: application/json

{
    "title":"Rock in Rio 2024",
    "category":"event",
    "price":125,
    "plataform":"blacktag",
    "description":"Ingresso 2 dias do tusca 2023: DJ GBR, Matheus e Kauan.",
    "dateEvent":{
        "year":2023,
        "month":1,
        "day":27,
        "hour":9,
        "minutes":0
    }
}

###
GET http://localhost:8080/tickets/64796a38743b602836d5e981

###
POST http://localhost:8080/tickets/trade
Content-Type: application/json

{
    "emailSaller":"otavio.bene@outlook.com",
    "emailBuyer":"suporte@hebrombeneficios.com.br",
    "ticketId":"a35adb4b-8fc7-4d0e-9217-d4f615eaa465"
}

# Trades
###
GET http://localhost:8080/trades/64796a38743b602836d5e981