version: '1'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    #volumes:
      #- mongo_db:/data/db
    ports:
      - 27017:27017
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
  main:
    build:
      context: ./trades
      dockerfile: Dockerfile
    container_name: paid_main
    env_file:
      - ./main/.env
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - rabbitmq
  trades:
    build:
      context: ./trades
      dockerfile: Dockerfile
    container_name: paid_trades
    ports:
      - 9090:9090
    depends_on:
      - rabbitmq      
#volumes:
  #mongo_db: {}

