version: '3'
services:
  mongo_db:
    image: mongo:latest
    container_name: db_mongo
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017
  sys:
    build: .
    container_name: paid_sys
    env_file:
      - .env.production
    ports:
      - 8080:8080
    depends_on:
      - mongo_db

networks:
  paid_network:
    driver: bridge

volumes:
  mongo_db: {}

